require("plugins")
require("config.default")
require("config.telescope")
require("config.lsp")
require("config.treesitter")
require("config.neogit")
-- require("config.emmet")
require("config.airline")
require("config.nvim-cmp")
require("config.gitsign")
require("config.surround")
require("config.auto-pair")
require("config.project")
require("config.quick-scope")
require("config.yanky")
require("keymaps")
require("colorscheme")
