---@class AutocmdCallbackEvent
---@field id number
---@field event string
---@field group number
---@field match string
---@field buf number
---@field file string
---@field data any

---@class NullWindowOptions
---@field left boolean
---@field right boolean
