return {
  filetypes = {
    "javascript",
    "javascriptreact",
    "javascript.jsx",
    "typescript",
    "typescriptreact",
    "typescript.tsx",
    "vue",
  },

  configurations = {
    {
      type = "node2",
      request = "launch",
      name = "Launch file",
      program = "${file}",
      cwd = "${workspaceFolder}",
      sourceMaps = true,
      restart = true,
    },
    {
      type = "node2",
      request = "attach",
      name = "Attach",
      processId = require("dap.utils").pick_process,
      cwd = "${workspaceFolder}",
      sourceMaps = true,
      restart = true,
    },
    {
      type = "node2",
      request = "attach",
      name = "Attach Program (port 9229)",
      cwd = "${workspaceFolder}",
      sourceMaps = true,
      restart = true,
      skipFiles = { "<node_internals>/**" },
      port = 9229,
    },
    {
      type = "node2",
      request = "attach",
      name = "Attach Program From Docker (port 9229)",
      cwd = "${workspaceFolder}",
      sourceMaps = true,
      restart = true,
      skipFiles = { "<node_internals>/**" },
      port = 9229,
      localRoot = "${workspaceFolder}",
      remoteRoot = "/var/www",
    },
  },
}
